timesteps: [0,201]


name: "${exp_setting}_HyFI_MEG_${brain_backbone}_${vision_backbone}"

models:
  brain:
    target: "base.eeg_backbone.${brain_backbone}"
    params:
        c_num: 271
        z_dim: ${z_dim}
        timesteps: ${timesteps}

data:
  data_dir: /your_data_path/data/Preprocessed_data_250Hz_whiten
  feature_dir : /your_data_path/visual_feature_MEG/blur/
  selected_ch: False
  model_type: ${vision_backbone}
  train_batch_size: 512
  val_batch_size: 200
  test_batch_size: 200
  uncertainty_aware: True
  blur_type:
    target: base.inpating_data.FoveaBlur
    params:
          h: 224
          w: 224
          blur_kernel_size: ${blur_kernel_size}
          curve_type: exp
          system_g:  ${system_g}

  train_avg: True
  test_avg: True
  timesteps: ${timesteps}

train:
  epoch: ${epoch}
  optimizer: AdamW
  lr: ${lr}
  
save_dir: 'exp'

Blur: 
  soft_k: 51  
  soft_g: 3
  hard_k: 31
